name: Build AVR GCC

on:
  push:
  workflow_dispatch:

jobs:
  build-avr-gcc:
    runs-on: ubuntu-20.04

    steps:
      - name: Install dependencies
        run: |
         sudo apt-get update
         sudo apt-get upgrade -y
         sudo apt-get install -y git wget autoconf2.64 build-essential netpbm libmpc-dev libmpfr-dev libgmp-dev libmpfr6 texinfo doxygen flex bison libexpat1-dev slang-xfig

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
         ls
         bash ./build.sh

      - name: Compiling test files
        run: |
         /opt/avr-gcc/bin/avr-g++ --version
         /opt/avr-gcc/bin/avr-g++ -mmcu=atmega328p test/main1.cpp
         /opt/avr-gcc/bin/avr-g++ -mmcu=atmega328p test/main2.cpp

      #- name: Fake toolchain
      #  run: |
      #   mkdir -p /opt/avr-gcc/bin
      #   cp $(which true) /opt/avr-gcc/bin/avr-g++

      - name: Create tarball
        run: |
         tar cjf modm-avr-gcc.tar.bz2 -C /opt avr-gcc

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: modm-avr-gcc
          path: modm-avr-gcc.tar.bz2

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: AVR GCC ${{ github.ref }}
          draft: false
          prerelease: false
          files: modm-avr-gcc.tar.bz2
